// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz5WTEGQCmAN4FHpLi0K8S-BVdXkaY9-A',
    appId: '1:884902753802:web:9e68b5675cca8a05b851f3',
    messagingSenderId: '884902753802',
    projectId: 'flutter-mobileapp-d5d4b',
    authDomain: 'flutter-mobileapp-d5d4b.firebaseapp.com',
    storageBucket: 'flutter-mobileapp-d5d4b.appspot.com',
    measurementId: 'G-CQDG352P6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFekQLYRX4fYUFNlVE3nv1gD62dVokSlw',
    appId: '1:952913872179:android:6c5ae3778b04fc7b1d6a46',
    messagingSenderId: '952913872179',
    projectId: 'hunterflutterdatabases',
    storageBucket: 'hunterflutterdatabases.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJqj4fC6cp-_gLDuUlzibcv22EXu_wVEw',
    appId: '1:952913872179:ios:2fb36f9c499119071d6a46',
    messagingSenderId: '952913872179',
    projectId: 'hunterflutterdatabases',
    storageBucket: 'hunterflutterdatabases.appspot.com',
    iosBundleId: 'com.example.cardGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJqj4fC6cp-_gLDuUlzibcv22EXu_wVEw',
    appId: '1:952913872179:ios:2fb36f9c499119071d6a46',
    messagingSenderId: '952913872179',
    projectId: 'hunterflutterdatabases',
    storageBucket: 'hunterflutterdatabases.appspot.com',
    iosBundleId: 'com.example.cardGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALvSOQPkMrQYKmhSe1r6Ci1O3dKC3Jm4I',
    appId: '1:952913872179:web:56b4b58b419451ba1d6a46',
    messagingSenderId: '952913872179',
    projectId: 'hunterflutterdatabases',
    authDomain: 'hunterflutterdatabases.firebaseapp.com',
    storageBucket: 'hunterflutterdatabases.appspot.com',
    measurementId: 'G-HTK3974L5Y',
  );

}